// console.log(2 + "2");
// console.log(2 - "2");
// console.log("3" - 2);
// console.log(+"2");
// console.log("2" * 3);
// console.log(3 + 4 + "5");
// console.log(+"2" + "3");
// console.log([1, 2] == "1,2");
// console.log([1] == true);
// console.log([] == false);
// console.log({} == {});
// console.log(undefined == null);
// console.log([] + {});
// console.log(0.1 + 0.2 == 0.3);
// console.log([2] == "2");
// console.log([1] + [2]);
// console.log(false == "false");
// console.log(1 + 2 + "3");
// console.log([] == []);
// console.log([] == ![]);
// console.log([1, 2] == "1,2");
// console.log(0 == false);
// console.log(1 == true);
// console.log(NaN == NaN);
// console.log(NaN === NaN);
// console.log("2" == 2);
// console.log(2 == "2");
// console.log({} === {});
// console.log([1] == 1);
// console.log([] == 0);
// console.log("" == false);
// console.log([2] + [3]);
// console.log("" == 0);
// console.log(3 == 3.0);
// console.log({} == false);
// console.log([] + null);
// console.log(5 + 5 + "5");
// console.log([] + 5);
// console.log([] + null);
// console.log(3 + 4 + "5" - 3);
// console.log(4 + 5 + "3");
// console.log("" == []);
// console.log([] + "1");
// console.log(true + 1);
// console.log([1] + "string");
// console.log("123" == 123);
// console.log([] + []);
// console.log(1 + true);
// console.log(2 == "2");
// console.log(false + false);
// console.log(1 + [2, 3]);
// console.log(null == undefined);
// console.log(null === undefined);
// console.log(1 < 2 < 3);
// console.log(3 > 2 > 1);
// console.log(true + "test");
// console.log(2 + "2" + 2);
// console.log(typeof NaN);
// console.log([1, 2, 3] == "1,2,3");
// console.log(0 === -0);
// console.log(3 - "2");
// console.log(false == 0);
// console.log(true == 1);
// console.log(null + 1);
// console.log(undefined + 1);
// console.log(true + true);
// console.log([1] == "1");
// console.log([1] + "2");
// console.log([3, 4] == "3,4");
// console.log([] + []);
// console.log({} == true);
// console.log("" == 0);
// console.log("1" == 1);
// console.log([1, 2] == "1,2");
// console.log([0] == false);
// console.log([] + {} == "[object Object]");
// console.log([3, 4] == "3,4");
// console.log(false == 0);
// console.log([] == 0);
// console.log([1, 2] == true);
// console.log(0 == false);
// console.log([3] == true);
// console.log([2, 3] + "test");
// console.log([0] + null);
// console.log([1, 2] == 12);
// console.log([] + "test");
// console.log({} == "test");
// console.log([3, 4] == "3,4");
// console.log("" == 0);
// console.log("" == false);
// console.log("foo" + "bar");
// console.log("true" == true);
// console.log("false" == false);
// console.log(true + true + "test");
// console.log(3 == 3);
// console.log([1, 2] == [1, 2]);
// console.log(null + undefined);
// console.log([] + undefined);
// console.log(3 + "4" + 5);
// console.log([1, 2] + [3, 4]);
// console.log("1" + "2" + 3);
// console.log(5 + "5" + 1);
// console.log(5 * "5");
// console.log([] == false);
// console.log("4" - 1);
// console.log([1] == "1");
// console.log([1, 2] == "1,2");
// console.log([5, 6] == "5,6");
// console.log(10 === "10");
// console.log("10" === 10);
// console.log("10" == 10);
// console.log("2" * "3");
// console.log(5 == "5");
// console.log(true + 1);
// console.log([] == true);
// console.log("3" - "2");
// console.log(10 / 5);
// console.log([] == 0);
// console.log([1] + 1);
// console.log("" == []);
// console.log([2, 3] == "2,3");
// console.log([1] == [1]);
// console.log("false" == false);
// console.log(false == 0);
// console.log(0 == false);
// console.log(1 === "1");
// console.log([] == ![]);
// console.log([] == []);
// console.log([1] == [1]);
// console.log(null + 1);
// console.log(undefined + 1);
// console.log("3" == 3);
// console.log("3" === 3);
// console.log("0" == false);
// console.log("0" === false);
// console.log("" == false);
// console.log("" === false);
// console.log(0 == false);
// console.log(0 === false);
// console.log(1 == "1");
// console.log(1 === "1");
// console.log([1] == true);
// console.log([1] == false);
// console.log([2] == "2");
// console.log({} == false);
// console.log({} == true);
// console.log([] + []);
// console.log([1] + "test");
// console.log([1] + [2]);
// console.log("" + []);
// console.log(true + []);
// console.log({} + []);
// console.log([] + {});
// console.log([null] == null);
// console.log([undefined] == undefined);
// console.log(NaN == NaN);
// console.log(NaN === NaN);
// console.log(true + "1");
// console.log(1 + "1");
// console.log([2] == "2");
// console.log([] == true);
// console.log("2" - 1);
// console.log([5] == 5);
// console.log([2] == "2");
// console.log(1 == [1]);
// console.log([2] == 2);
// console.log([3] == "3");
